CREATE SEQUENCE IF NOT EXISTS chat_message_seq START WITH 1 INCREMENT BY 1;

-- ── notification_subscriptions (H2) ──────────────────────────
CREATE TABLE IF NOT EXISTS notification_subscriptions
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT        NOT NULL,
    service_id       VARCHAR(30)   NOT NULL,
    filter           VARCHAR(2000) NOT NULL DEFAULT '{}',
    last_notified_at TIMESTAMP,
    created_at       TIMESTAMP     NOT NULL DEFAULT NOW(),
    deleted_at       TIMESTAMP,

    CONSTRAINT uq_ns_user_service UNIQUE (user_id, service_id)
);

-- ── notification_dispatches (H2) ─────────────────────────────
CREATE TABLE IF NOT EXISTS notification_dispatches
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subscription_id  BIGINT        NOT NULL REFERENCES notification_subscriptions (id),
    change_log_id    BIGINT        NOT NULL,
    status           VARCHAR(10)   NOT NULL DEFAULT 'PENDING',
    attempt_count    SMALLINT      NOT NULL DEFAULT 0,
    sent_at          TIMESTAMP,
    generated_title  VARCHAR(200),
    generated_body   VARCHAR(4000),
    template_source  VARCHAR(10),
    last_error       VARCHAR(4000),
    created_at       TIMESTAMP     NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMP     NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_nd_subscription_change UNIQUE (subscription_id, change_log_id),
    CONSTRAINT chk_nd_status CHECK (status IN ('PENDING', 'SUCCESS', 'FAILED', 'DEAD')),
    CONSTRAINT chk_nd_template_source CHECK (template_source IN ('AI', 'FALLBACK') OR template_source IS NULL)
);
